### 1. Name string

In [1]:
first_name = 'Farooq' # type in your first name here
first_name

'Farooq'

In [2]:
last_name = 'Mahmud' # type in your last name here
last_name

'Mahmud'

#### Please concatenate your first and last name with a space between them, then print your name

In [3]:
# Please concatenate your first and last name with a space between them, then print your name
first_name + ' ' + last_name

'Farooq Mahmud'

### 2. Given the following list, write a program to display the first and last colors

In [4]:
# Given the following list, write a program to display the first and last colors
color_list = ["Red","Green","White" ,"Black"]

[color_list[0], color_list[-1]]

['Red', 'Black']

### 3. Compute and print the value of `n+nn+nnn`.

In [5]:
# Compute and print the value of n+nn+nnn.
n = 5
n + (n**2) + (n**3)

155

### 4. Numbers

### 4.1 Calculate `num = 1325 / 3`

In [6]:
num = 1325/3
num

441.6666666666667

### 4.2 Round `num` to 3 decimals

In [7]:
round(num, 3)

441.667

### 4.3 Return the remainder of `num`

In [8]:
num % 2

1.6666666666666856

### 4.4 Compute `num` to the power of 3

In [9]:
num ** 3

86155671.29629631

### 5. Lists

In [10]:
num1 = [386, 462, 47, 418, 907, 344, 236, 375, 823, 566, 597, 978, 328, 615, 953, 345,
    399, 162, 758, 219, 918, 237, 412, 566, 826, 248, 866, 950, 626, 949, 687, 217]
num2 = [815, 67, 104, 58, 512, 24, 892, 894, 767, 553, 81, 379, 843, 831, 445, 742, 717,
    958,743, 527]

### 5.1 Concatenate `num1` and `num2` to new list `num_new`

In [11]:
num_new = num1 + num2
num_new

[386,
 462,
 47,
 418,
 907,
 344,
 236,
 375,
 823,
 566,
 597,
 978,
 328,
 615,
 953,
 345,
 399,
 162,
 758,
 219,
 918,
 237,
 412,
 566,
 826,
 248,
 866,
 950,
 626,
 949,
 687,
 217,
 815,
 67,
 104,
 58,
 512,
 24,
 892,
 894,
 767,
 553,
 81,
 379,
 843,
 831,
 445,
 742,
 717,
 958,
 743,
 527]

### 5.2 Print the length of list `num_new`

In [12]:
print(len(num_new))

52

### 5.3 Add the cube of `10` at the end of the list `num_new`

In [13]:
num_new.append(pow(10, 3))
num_new[-1]

1000

### 5.4 Print the length of list `num_new` again

In [14]:
print(len(num_new))

53

### 5.5 Write a Python program to print all even numbers in list `num_new` and stop printing any after `237` in the sequence.

### 6 More examples of Python code can be found at https://www.geeksforgeeks.org/python-cheat-sheet/
Please practice more if you are new to Python.

In [15]:
[num for num in num_new if num % 2 == 0 and num <= 236]

[236, 162, 104, 58, 24]